services:

  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: restaurant-automation
      POSTGRES_USER: restaurant-automation
      POSTGRES_PASSWORD: root