spring:
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: 'true'
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'true'
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    password: root
    username: restaurant-automation
    url: jdbc:postgresql://localhost:5432/restaurant-automation
  jackson:
    default-property-inclusion: non_null
  flyway:
    sql-migration-prefix: V
    sql-migration-separator: __
    sql-migration-suffixes: .sql
    user: restaurant-automation
    password: root

jwt:
  expiration-time: ${JWT_EXPIRATION_TIME}
  secret: ${JWT_SECRET_KEY}

logging:
  level:
    root: INFO